// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nuucklapjdpalbzxscjd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im51dWNrbGFwamRwYWxienhzY2pkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYyNzAxOTcsImV4cCI6MjA1MTg0NjE5N30.ps_YT-nCjNLvTmx_SzJkRugxcDeU3CgWUyL0X7Vb8tQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);